language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
    - .cache
script:
  - export YARN_CACHE_FOLDER=$TRAVIS_BUILD_DIR/.cache/yarn
  - export NODE_ENV=development
  - export TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
  - yarn install --frozen-lockfile
  - yarn lint
  - yarn build
  - yarn generate-version
deploy:
  branch: main
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
