theme: jekyll-theme-cayman
title: @koeroesi86/react-reviver
description: An awesome layout reviver for data driven React applications.
github:
  zip_url: https://github.com/Koeroesi86/react-reviver/archive/refs/heads/main.zip
  npm_url: https://www.npmjs.com/package/@koeroesi86/react-reviver
  repository_url: https://github.com/Koeroesi86/react-reviver